# Name: Makefile
# Author: Zhang Riyueming

BUILD_DIR = ../build/
BUILD_DIR := $(shell cd $(BUILD_DIR) && /bin/pwd)

# This is a prototype Makefile. Modify it according to your needs.
# You should at least check the settings for
# DEVICE ....... The AVR device you compile for
# CLOCK ........ Target AVR clock rate in Hertz
# OBJECTS ...... The object files created from your source files. This list is
#                usually the same as the list of source files with suffix ".o".
# PROGRAMMER ... Options to avrdude which define the hardware you use for
#                uploading to the AVR and the interface where this hardware
#                is connected. We recommend that you leave it undefined and
#                add settings like this to your ~/.avrduderc file:
#                   default_programmer = "stk500v2"
#                   default_serial = "avrdoper"
# FUSES ........ Parameters for avrdude to flash the fuses appropriately.

DEVICE     = atmega162
CLOCK      = 8000000
PROGRAMMER = -c USBasp
OBJECTS    = $(BUILD_DIR)/${file_base_name}.o
FUSES      = -U hfuse:w:0x99:m -U lfuse:w:0xe2:m

# ATMega8 fuse bits used above (fuse bits for other devices are different!):
# Example for 8 MHz internal oscillator
# Fuse high byte:
# 0xd9 = 1 1 0 1   1 0 0 1 <-- BOOTRST (boot reset vector at 0x0000)
#        ^ ^ ^ ^   ^ ^ ^------ BOOTSZ0
#        | | | |   | +-------- BOOTSZ1
#        | | | |   +---------- EESAVE (set to 0 to preserve EEPROM over chip erase)
#        | | | +-------------- CKOPT (clock option, depends on oscillator type)
#        | | +---------------- SPIEN (if set to 1, serial programming is disabled)
#        | +------------------ WDTON (if set to 0, watchdog is always on)
#        +-------------------- RSTDISBL (if set to 0, RESET pin is disabled)
# Fuse low byte:
# 0x24 = 0 0 1 0   0 1 0 0
#        ^ ^ \ /   \--+--/
#        | |  |       +------- CKSEL 3..0 (8M internal RC)
#        | |  +--------------- SUT 1..0 (slowly rising power)
#        | +------------------ BODEN (if 0, brown-out detector is enabled)
#        +-------------------- BODLEVEL (if 0: 4V, if 1: 2.7V)
#
# For computing fuse byte values for other devices and options see
# the fuse bit calculator at http://www.engbedded.com/fusecalc/


# Tune the lines below only if you know what you are doing:

AVRDUDE = avrdude $(PROGRAMMER) -p $(DEVICE)
COMPILE = avr-gcc -Wall -Os -DF_CPU=$(CLOCK) -DSINGLE_FILE=1 -mmcu=$(DEVICE)

# symbolic targets:
all:	$(BUILD_DIR)%${file_base_name}.hex

$(BUILD_DIR)%.c.o:
	$(COMPILE) -c $< -o $@

$(BUILD_DIR)%.cpp.o:
	$(COMPILE) -c $< -o $@

$(BUILD_DIR)%${file_base_name}.o: ${file_name}
	$(COMPILE) -c $< -o $@

.S.o:
	$(COMPILE) -x assembler-with-cpp -c $< -o $@
# "-x assembler-with-cpp" should not be necessary since this is the default
# file type for the .S (with capital S) extension. However, upper case
# characters are not always preserved on Windows. To ensure WinAVR
# compatibility define the file type manually.

.c.s:
	$(COMPILE) -S $< -o $@

.cpp.s:
	$(COMPILE) -S $< -o $@

flash:	all
	$(AVRDUDE) -U flash:w:$(BUILD_DIR)/${file_base_name}.hex:i

fuse:
	$(AVRDUDE) $(FUSES)

# Xcode uses the Makefile targets "", "clean" and "install"
install: flash fuse

# if you use a bootloader, change the command below appropriately:
load: all
	bootloadHID ${file_base_name}.hex

clean:
	rm -f ${file_base_name}.hex ${file_base_name}.elf $(OBJECTS)

# file targets:
$(BUILD_DIR)%${file_base_name}.elf: $(OBJECTS)
	$(COMPILE) -o $(BUILD_DIR)/${file_base_name}.elf $(OBJECTS)

$(BUILD_DIR)%${file_base_name}.hex: $(BUILD_DIR)%${file_base_name}.elf
	rm -f $(BUILD_DIR)/${file_base_name}.hex
	avr-objcopy -j .text -j .data -O ihex $(BUILD_DIR)/${file_base_name}.elf $(BUILD_DIR)/${file_base_name}.hex
	avr-size --format=avr --mcu=$(DEVICE) $(BUILD_DIR)/${file_base_name}.elf
# If you have an EEPROM section, you must also create a hex file for the
# EEPROM and add it to the "flash" target.

# Targets for code debugging and analysis:
disasm:	${file_base_name}.elf
	avr-objdump -d $(BUILD_DIR)/${file_base_name}.elf

cpp:
	$(COMPILE) -E ${file_name}
